### ISSUE TITLE
What makes Kefir faster than Bacon?

### ISSUE THREAD

**Issue by mhelvens** [pozadi/kefir#48]
I've seen the [tree demo](http://pozadi.github.io/kefir/demos/tree.html). Quite impressive. I'd be curious to know what makes Kefir.js fast / Bacon.js slow.

What do Kefir users sacrifice for this increased speed, if anything?

**Comment by pozadi** [comment]
It's a little hard to answer as haven't closely compared Bacon's implementations to Kefir's. For what I know:

 - Kefir uses Classes a lot, and stores methods in `prototypes`, while Bacon often creates methods for each instance. But this probably more affects memory footprint than performance.
 - Bacon often implements transformation methods based on other methods. For example this is from the implementation of `.debounce`: `@flatMapFirst (value) -> Bacon.once(value).concat(Bacon.later(delay).filter(false)))`. While in Kefir most methods implemented without intermediate observables between source and result.
 - Also there is a bunch of micro optimizations in Kefir, such as using own `concat()` function instead of native `Array::concat` and so on.

About what we sacrifice, I think there is only one feature that aren't implemented in Kefir in particular because of performance penalty — [atomic updates](https://github.com/baconjs/bacon.js/#atomic-updates). But it's not only about performance, it also pretty tricky to do right. Maybe Kefir will get this one day. (RxJS also doesn't have this, btw :)

Closing this, but feel free to continue discussion.

**Comment by asaaki** [comment]
This would be something for a `FAQ` section or comparison overview. Pretty good insight. Thank you!
