### ISSUE TITLE
Should pool/bus add multiple instances of the same observable?

### ISSUE THREAD

**Issue by zaim** [pozadi/kefir#73]
Currently, the behavior of pool/bus is to plug in *all* observables, regardless of whether the instance was previously added or not:

```js
var pool = Kefir.pool().log()
var obs = Kefir.emitter()
pool.plug(obs)
pool.plug(obs)
pool.plug(obs)
obs.emit('test')
```
Outputs:
```
[pool] <value> data
[pool] <value> data
[pool] <value> data
```

I'm new to Kefir/RP, so this might as well be the desired behavior, not a bug. In any case, consider allowing pools to only maintain a *unique* set of source observables, perhaps via a separate `Kefir.poolSet` function?

```js
var pool = Kefir.poolSet().log()
var obs = Kefir.emitter()
pool.plug(obs)
pool.plug(obs)
pool.plug(obs)
obs.emit('test')
```
Outputs:
```
[pool] <value> data
```

**Comment by pozadi** [comment]
This is intentional. I was thinking whether it should be allowed or not, but didn't had a strong felling for either option. So I decided to allow that. Because when it allowed user can relatively easy do both things, but if it was disabled it would be tricky to create a pool with more than one instance of same obs.

About `Kefir.poolSet()`, don't know. Doesn't seems like a common use case to be in the core.
