### ISSUE TITLE
Some naming changes?

### ISSUE THREAD

**Issue by gyzerok** [pozadi/kefir#74]
I suppose that Kefir was start as a funny hobby. So thats why it has this name.
Since for now its a serious project it requires serious name. There are two reasons for it:
1. Kefir is looking ugly (sorry, but extremely ugly)
2. Its russian word so it means nothing for most part of projects audience

I suppose that you can choose more nice looking and more semantic heavy name. Thank you :)

**Comment by pozadi** [comment]
> Kefir is looking ugly (sorry, but extremely ugly)

Disagree. Anyone also think it ugly?

>  Its russian word so it means nothing for most part of projects audience

Also not true, although kefir as a drink most popular in post soviet countries, I believe it might be known in a lot of places around the world. Didn't do a research though, maybe you are right on this.

Closing because probably won't happen, but feel free to continue discussion. Do you have any ideas on alternative name, btw?

**Comment by asaaki** [comment]
I like the name.
So if there was a poll I would vote for keeping the name.

_And also keep in mind: kefir is healthier than bacon. :wink:_

**Comment by pozadi** [comment]
> And also keep in mind: kefir is healthier than bacon.

That's the original idea behind the name, yes)

**Comment by dchem** [comment]
For what it's worth, I live in US and I drink Kefir occasionally. Also, I like funny name as opposed to serious name. Finally, I don't think naming this something like "frp_module" or "esp-helper" makes it more memorable.
